---
name: zampy
channels:
  - conda-forge
dependencies:
  - python>=3.8,<3.11
  - xESMF
  - requests
  - netcdf4
  - numpy
  - pandas
  - matplotlib
  - xarray
  - rioxarray  # required for TIFF files
  - tqdm
  - dask[diagnostics]
  - pint
  - cf_xarray  # required to auto-pint CF compliant datasets
  - pint-xarray
  - flox
